# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://atomx.cc/"
title: Atom.X
copyright: "Â© [Atom.X](https://atomx.cc)"
# paginate: 5
pagination:
  pagerSize: 5
theme: [PaperMod]
ignoreLogs:
  - 'warning-partial-superfluous-prefix'
relativeURLs: true
canonifyURLs: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - identifier: about
          name: About
          url: /about/
          weight: 1
        - identifier: values 
          name: "Values"
          url: posts/about/values/  
          weight: 2
        - identifier: social
          name: "Social works"
          url: posts/about/cases-social-works/
          weight: 3
        - identifier: business
          name: "Business"
          url: posts/about/cases-business/
          weight: 4
        - identifier: business
          name: "Education"
          url: posts/about/education-training/
          weight: 5
        - identifier: archives
          name: Archive
          url: /archives/
          weight: 6
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 7

        - identifier: categories
          name: Categories
          url: categories/
          weight: 8
        
        - identifier: search
          name: Search
          url: /search/
          weight: 9
       
        - identifier: Coolshell
          name: Coolshell.in
          url: https://coolshell.in/
          weight: 10

  zh:
    languageName: "ç®€ä½“ä¸­æ–‡"
    contentDir: content/zh
    #languagedirection: ltr
    weight: 10
    title: Atom.X
    taxonomies:
      category: categories
      tag: tags
      series: series

    menu:
      main:
        - identifier: about
          name: "å…³äºŽ"
          url: about/
          weight: 1

        - identifier: archives
          name: "å½’æ¡£"
          url: archives/
          weight: 3
        
        - identifier: tags
          name: "æ ‡ç­¾"
          url: tags/
          weight: 5
        
        - identifier: categories
          name: "åˆ†ç±»"
          url: categories/
          weight: 8
        
        - identifier: search
          name: "æœç´¢"
          url: search/
          weight: 9

        # - identifier: Coolshell
        #   name: é…·å£³ä¼—åˆ›
        #   url: https://coolshell.in/zh-cn/
        #   weight: 10
    
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "ç®€ä½“ä¸­æ–‡"
      profileMode:
        enabled: true
        title: "æ¬¢è¿Žæ¥è®¿ï¼"
        imageUrl: "/images/atom-f.jpg"
        imageTitle: Atom
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "â˜„ï¸ é«˜å¹¶å‘-é«˜å¯ç”¨ | â˜ï¸ å¼‚åœ°å¤šæ´» | ðŸŒ™ è´Ÿè½½å‡è¡¡ | âš¡ï¸ å¿«é€Ÿå“åº” | ðŸ“± è‡ªé€‚åº” "
        buttons:
        
          - name: "ç¤¾ä¼šæ´»åŠ¨"  
            url: posts/about/cases-social-works/
          - name: "å•†ä¸šæ¡ˆä¾‹"
            url: posts/about/cases-business/
          - name: "æ•™è‚²åŸ¹è®­"
            url: posts/about/education-training/
          - name: "ä»·å€¼è§‚"
            url: posts/about/values/
          - name: "åŽ†å²è®°å½•"
            url: posts/about/No1/
            
  
  nl:
    languageName: "Nederlands"
    contentDir: content/nl
    #languagedirection: ltr
    weight: 3
    title: Atom.X
    taxonomies:
      category: categories
      tag: tags
      series: series

    menu:
      main:
        - identifier: about
          name: "Over"
          url: about/
          weight: 1

        - identifier: archives
          name: "Archief"
          url: archives/
          weight: 3
        
        - identifier: tags
          name: "Tags"
          url: tags/
          weight: 5
        
        - identifier: categories
          name: "CategorieÃ«n"
          url: categories/
          weight: 8
        
        - identifier: search
          name: "Zoeken"
          url: search/
          weight: 9

        - identifier: Coolshell
          name: Coolshell.in
          url: https://coolshell.in/nl/
          weight: 10
    
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "Nederlands"
      profileMode:
        enabled: true
        title: "Welkom!"
        imageUrl: "/images/atom-f.jpg"
        imageTitle: ProfileMode image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "â˜„ï¸ Hoge concurrentie - Hoge beschikbaarheid | â˜ï¸ Multi-site failover | ðŸŒ™ Load balancing | âš¡ï¸ Snelle respons | ðŸ“± Adaptief"
        buttons:
          - name: "Waarden"
            url: posts/about/values/
          - name: "Maatschappelijke activiteiten"  
            url: posts/about/cases-social-works/
          - name: "Zakelijke cases"
            url: posts/about/cases-business/
          - name: "Onderwijs en training"
            url: posts/about/education-training/

  de:
    languageName: "Deutsch"
    contentDir: content/de
    weight: 2
    title: Atom.X
    taxonomies:
      category: categories
      tag: tags
      series: series

    menu:
      main:
        - identifier: about
          name: "Ãœber"
          url: about/
          weight: 1

        - identifier: archives
          name: "Archiv"
          url: archives/
          weight: 3
        
        - identifier: tags
          name: "Tags"
          url: tags/
          weight: 5
        
        - identifier: categories
          name: "Kategorien"
          url: categories/
          weight: 8
        
        - identifier: search
          name: "Suche"
          url: search/
          weight: 9

        - identifier: Coolshell
          name: Coolshell
          url: https://coolshell.in/de/
          weight: 10

    params:
      languageAltTitle: "Deutsch"
      profileMode:
        enabled: true
        title: "Willkommen!"
        imageUrl: "/images/atom-f.jpg"
        imageTitle: Profilbild
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "â˜„ï¸ Hohe ParallelitÃ¤t - Hohe VerfÃ¼gbarkeit | â˜ï¸ Geografisch verteilte Aktiv-Aktiv-Architektur | ðŸŒ™ Lastausgleich | âš¡ï¸ Schnelle Reaktionszeit | ðŸ“± Adaptiv"
        buttons:
          - name: "Werte"
            url: posts/about/values/
          - name: "Soziale AktivitÃ¤ten"  
            url: posts/about/cases-social-works/
          - name: "GeschÃ¤ftsfÃ¤lle"
            url: posts/about/cases-business/
          - name: "Ausbildung"
            url: posts/about/education-training/
                        
  # ru:
  #   languageName: "PÑƒÑÑÐºÐ¸Ð¹"
  #   contentDir: content/ru
  #   weight: 3
  #   title: "ÐÑ‚Ð¾Ð¼.X"
  #   taxonomies:
  #     category: categories
  #     tag: tags
  #     series: series
  #   menu:
  #     main:
  #       - identifier: about
  #         name: "Ð¾Ð±Ð¾ Ð¼Ð½Ðµ"
  #         url: about/
  #         weight: 1      
  #       - identifier: archives
  #         name: "ÐÑ€Ñ…Ð¸Ð²"
  #         url: archives/
  #         weight: 3
  #       - identifier: tags
  #         name: "Ð¢ÐµÐ³Ð¸"
  #         url: tags/
  #         weight: 5
  #       - identifier: categories
  #         name: "ÐšÐ°Ñ‚ÐµÐ³Ð¾Ñ€Ð¸Ð¸"
  #         url: categories/
  #         weight: 8
  #       - identifier: search
  #         name: "ÐŸÐ¾Ð¸ÑÐº"
  #         url: search/
  #         weight: 9
  #       - identifier: Coolshell
  #         name: Coolshell.in
  #         url: https://coolshell.in/ru/
  #         weight: 10
    
  #   # custom params for each language should be under [langcode].parms - hugo v0.120.0
  #   params:
  #     languageAltTitle: RÑƒÑÑÐºÐ¸Ð¹
  #     profileMode:
  #       enabled: true
  #       title: PaperMod
  #       imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
  #       imageTitle: ProfileMode image
  #       # imageWidth: 120
  #       # imageHeight: 120
  #       subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ðŸŒ™ Smooth | ðŸ“± Responsive"
  #       buttons:
  #         - name: Blog
  #           url: posts
  #         - name: Profile Mode
  #           url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode

  

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  math: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Atom.X - An Passionate Software Developer and IT worker"
  keywords: 
    - Cloud Computing
    - High Availability
    - Load Balancing
    - Disaster Recovery
    - Multi-Site High Availability
  author: "Atom.X"
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true

  # Global default front matter
  ShowToc: true
  TocOpen: true
  # TOC position configuration
  toc:
    enabled: true
    position: right    # right side TOC
    # position: left    # left side TOC

  # Global date settings for front matter "date:" field
  
  DateFormat: "2006-1-2"    # Global date format
  # Front matter date settings
  # Date parsing settings
  date:
    format: "2006-1-2"      # Primary format
    layouts:
      - "2006-1-2"
    #  - "2006-01-02"
    validation: false       # Disable validation
  

  # comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    buttons:
        - name: "Blog"
          url: posts/
        - name: "Business Cases" 
          url: posts/about/cases-business/
        - name: "Social Works"
          url: posts/about/cases-social-works/
        - name: "Values"
          url: posts/about/values/  

  homeInfoParams:
    Title: ðŸ‘‹ Welcome !  
    Content: >
      I am a passionate developer who loves to code and write about technology.
      
      - My favourite **Topics**:
            
      - Think of danger in times of safety;

      - Disaster Recovery;

      - Load balancing;

      - Multi-Site High Availability(Active-Active across multiple locations);
    

  socialIcons:
    - name: Telegram
      title: Talk on Telegram
      url: "https://t.me/atomxxx"
    - name: Email
      title: Send an Email
      url: "mailto:hi@atomx.cc"
    - name: Github
      title: View Source on Github
      url: ""
    - name: Discord
      title: Join discord community
      url: ""
    - name: LinkedIn
      title: Connect on LinkedIn
      url: ""
    - name: Podcast
      title: Listen to Podcast
      url: ""
    - name: X
      title: Follow on X/Twitter
      url: "https://twitter.com/Atomxx3"
    - name: Instagram
      title: Photos and Stories
      url: "https://instagram.com/atomxu3"

  # editPost:
  #  URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # Analytics and SEO
  analytics:
    google:
      SiteVerificationTag: "XYZabc123"  # Only content value
    bing:
      SiteVerificationTag: "XYZabc456"  
    yandex:
      SiteVerificationTag: "XYZabc789"  
  # For Google Analytics 4
  # googleAnalytics: "G-MEASUREMENT_ID"  # Replace with your tracking ID

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#    X/Twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true